export { HomePage } from "./HomePage/Home";
export { AboutPage } from "./AboutPage/About";
export { MusicPage } from "./MusicPage/Music";
export { GalleryPage } from "./GalleryPage/Gallery";
export { GraphicPage } from "./GraphicPage/Graphic";
export { LanguagePage } from "./LanguagePage/Language";
export { MusicProductionPage } from "./MusicProductionPage/MusicProduction";
export { TechnologyPage } from "./TechnologyPage/Technology";
export { NotFound } from "./NotFound";
